### ISSUE TITLE
Syntax error when importing resolutions_per_authority

### ISSUE THREAD

**Issue by abbatematteo** [alexa/alexa-apis-for-python#10]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request (generic to all classes)
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

When importing ask_smapi_model.v1.skill.nlu.evaluations as here:
`from ask_smapi_model.v1.skill.nlu.evaluations import EvaluateNLURequest, Source`
the import should not fail.

## Current Behavior

When importing the classes above, the following error is returned:
```
File "/anaconda3/lib/python3.7/site-packages/ask_smapi_model/v1/skill/nlu/evaluations/resolutions_per_authority.py", line 21
    from  import null&lt;String, object&gt;
               ^
SyntaxError: invalid syntax
```
## Possible Solution
Looks like [here](https://github.com/alexa/alexa-apis-for-python/blob/master/ask-smapi-model/ask_smapi_model/v1/skill/nlu/evaluations/resolutions_per_authority.py) a package name is missing at line 21.

## Steps to Reproduce (for bugs)
Try to import anywhere:
```
from ask_smapi_model.v1.skill.nlu.evaluations import EvaluateNLURequest, Source
```

## Context

Then all the evaluation classes can not be imported.
## Your Environment

* ASK SDK Models for Python used: 1.5.1
* ASK SDK for Python used: 1.0.0

## Python version info
* Python version used for development: 3.7

**Comment by nikhilym** [comment]
Hey @abbatematteo , thanks for raising this issue. There seems to be a problem with the code generation process that lead to incorrect `imports`. We will be fixing this and releasing a patch to the smapi models soon. I will keep this issue updated with the changes.

**Comment by nikhilym** [comment]
Hey @abbatematteo , sorry for the late response. The new minor release [`ask-smapi-model 1.6.0`](https://pypi.org/project/ask-smapi-model/) fixes this issue. Please update and let us know if you still face problems. Thanks.
