### ISSUE TITLE
Hi All!Can someone tell me why my timer function is not calling? or can someone share a timer template?

### ISSUE THREAD

**Issue by danieldhz** [alexa/alexa-apis-for-python#11]

**Comment by franklin-lobb** [comment]
From the code (which I don't currently see in the issue), it appears that you haven't added the authorization header.

From the [docs](https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-timers-api-reference.html#alexa-timers-api-endpoint-and-authorization):

> Each API request must have an Authorization header.

re: an example - It's not python, but you might check out this sample: https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-timers 
The methodology should help.  Note the Timer Management Service Client.

**Comment by danieldhz** [comment]
Hi Franklin! Thank you so much for getting back to me!! As I really needed the help as the documentations was really inadequate with translating the python version of calling APIs.
My code is as follows:
`timer = {
    "duration": "PT15S",
    "timerLabel": "Change name",
    "creationBehavior": {
        "displayExperience": {
            "visibility": "VISIBLE"
        }
    },
    "triggeringBehavior": {
        "operation": {
            "type": "ANNOUNCE", 
            "textToAnnounce": [
                {
                    "locale": "en-US",
                    "text": "Break time"
                }
            ]
        },
        "notificationConfig": {
            "playAudible": True 
        }
    }
}


class LaunchRequestHandler(AbstractRequestHandler):
    """Handler for Skill Launch."""
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)

    def handle(self, handler_input):
        accessToken= ask_sdk_core.utils.get_api_access_token(handler_input)
        if accessToken == None:
            RequestSpeach = "Please use the companion app to give permission to this app"
            return (
                    #handler_input.response_builder.set_card(Card('LinkAccount'))
                    .ask_sdk_model.response_builder
                    .add_directive({
                        type: "Connections.SendRequest",
                        name: "AskFor",
                        payload: {
                        "@type": "AskForPermissionsConsentRequest",
                        "@version": "1",
                        "permissionScope": "alexa::alerts:timers:skill:readwrite"
                        },
                        token: "<string>"
                        })
                    .speak(RequestSpeach)
                    .ask()
                    .response
                    )
        else:
            speak_output = "would you like to set the timer for 20 minutes?"
            if ask_utils.is_request_type("AMAZON.YesIntent")(handler_input): 
                options = {"Authorization": "Bearer " + accessToken,
                            "Content-Type": "application/json"}
                requests.post("https://api.amazonalexa.com/v1/alerts/timers", timer, options)
                speak_output = "timer set for 20 seconds"`

**Comment by danieldhz** [comment]
`timer = {
    "duration": "PT15S",
    "timerLabel": "Change name",
    "creationBehavior": {
        "displayExperience": {
            "visibility": "VISIBLE"
        }
    },
    "triggeringBehavior": {
        "operation": {
            "type": "ANNOUNCE", 
            "textToAnnounce": [
                {
                    "locale": "en-US",
                    "text": "Break time"
                }
            ]
        },
        "notificationConfig": {
            "playAudible": True 
        }
    }
}`

**Comment by danieldhz** [comment]
`class LaunchRequestHandler(AbstractRequestHandler):
    """Handler for Skill Launch."""
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)
    
    def handle(self, handler_input):
        accessToken= ask_sdk_core.utils.get_api_access_token(handler_input)
        if accessToken == None:
            RequestSpeach = "Please use the companion app to give permission to this app"
            return (
                    #handler_input.response_builder.set_card(Card('LinkAccount'))
                    .ask_sdk_model.response_builder
                    .add_directive({
                        type: "Connections.SendRequest",
                        name: "AskFor",
                        payload: {
                        "@type": "AskForPermissionsConsentRequest",
                        "@version": "1",
                        "permissionScope": "alexa::alerts:timers:skill:readwrite"
                        },
                        token: "<string>"
                        })
                    .speak(RequestSpeach)
                    .ask()
                    .response
                    )
        else:
            speak_output = "would you like to set the timer for 20 minutes?"
            if ask_utils.is_request_type("AMAZON.YesIntent")(handler_input): 
                options = {"Authorization": "Bearer " + accessToken,
                            "Content-Type": "application/json"}
                requests.post("https://api.amazonalexa.com/v1/alerts/timers", timer, options)
                speak_output = "timer set for 20 seconds"`

**Comment by danieldhz** [comment]
`class LaunchRequestHandler(AbstractRequestHandler):
    """Handler for Skill Launch."""
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)
    def handle(self, handler_input):
        accessToken= ask_sdk_core.utils.get_api_access_token(handler_input)
        if accessToken == None:
            RequestSpeach = "Please use the companion app to give permission to this app"
            return (
                    #handler_input.response_builder.set_card(Card('LinkAccount'))
                    .ask_sdk_model.response_builder
                    .add_directive({
                        type: "Connections.SendRequest",
                        name: "AskFor",
                        payload: {
                        "@type": "AskForPermissionsConsentRequest",
                        "@version": "1",
                        "permissionScope": "alexa::alerts:timers:skill:readwrite"
                        },
                        token: "<string>"
                        })
                    .speak(RequestSpeach)
                    .ask()
                    .response
                    )
        else:
            speak_output = "would you like to set the timer for 20 minutes?"
            if ask_utils.is_request_type("AMAZON.YesIntent")(handler_input): 
                options = {"Authorization": "Bearer " + accessToken,
                            "Content-Type": "application/json"}
                requests.post("https://api.amazonalexa.com/v1/alerts/timers", timer, options)
                speak_output = "timer set for 20 seconds"`

**Comment by danieldhz** [comment]
`class LaunchRequestHandler(AbstractRequestHandler):
    """Handler for Skill Launch."""
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)`

**Comment by danieldhz** [comment]
`class LaunchRequestHandler(AbstractRequestHandler):
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)
    `

**Comment by danieldhz** [comment]
`class LaunchRequestHandler(AbstractRequestHandler):
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)
    
    def handle(self, handler_input):
        accessToken= ask_sdk_core.utils.get_api_access_token(handler_input)
        if accessToken == None:
            RequestSpeach = "Please use the companion app to give permission to this app"
            return (
                    #handler_input.response_builder.set_card(Card('LinkAccount'))
                    .ask_sdk_model.response_builder
                    .add_directive({
                        type: "Connections.SendRequest",
                        name: "AskFor",
                        payload: {
                        "@type": "AskForPermissionsConsentRequest",
                        "@version": "1",
                        "permissionScope": "alexa::alerts:timers:skill:readwrite"
                        },
                        token: "<string>"
                        })
                    .speak(RequestSpeach)
                    .ask()
                    .response
                    )
        else:
            speak_output = "would you like to set the timer for 20 minutes?"
            if ask_utils.is_request_type("AMAZON.YesIntent")(handler_input): 
                options = {"Authorization": "Bearer " + accessToken,
                            "Content-Type": "application/json"}
                requests.post("https://api.amazonalexa.com/v1/alerts/timers", timer, options)
                speak_output = "timer set for 20 seconds"`

**Comment by danieldhz** [comment]
`class LaunchRequestHandler(AbstractRequestHandler):
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)
    
    def handle(self, handler_input):
        accessToken= ask_sdk_core.utils.get_api_access_token(handler_input)
        if accessToken == None:
            RequestSpeach = "Please use the companion app to give permission to this app"
            return (
                    #handler_input.response_builder.set_card(Card('LinkAccount'))
                    .ask_sdk_model.response_builder
                    .add_directive({
                        type: "Connections.SendRequest",
                        name: "AskFor",
                        payload: {
                        "@type": "AskForPermissionsConsentRequest",
                        "@version": "1",
                        "permissionScope": "alexa::alerts:timers:skill:readwrite"
                        },
                        token: "<string>"
                        })
                    .speak(RequestSpeach)
                    .ask()
                    .response
                    )
        else:
            speak_output = "would you like to set the timer for 20 minutes?"
            if ask_utils.is_request_type("AMAZON.YesIntent")(handler_input): 
                options = {"Authorization": "Bearer " + accessToken,
                            "Content-Type": "application/json"}
                requests.post("https://api.amazonalexa.com/v1/alerts/timers", timer, options)
                speak_output = "timer set for 20 seconds"`

**Comment by danieldhz** [comment]
It would mean the world to me if you can guide me on where I went wrong, as I have been spending weeks on this and going nowhere :(

**Comment by franklin-lobb** [comment]
what's the status_code for the response from the `request.post` call?

**Comment by danieldhz** [comment]
Well I haven't reached that stage yet as for now I get:
  .ask_sdk_model.response_builder --> syntax error
and type object 'Response' has no attribute 'add_directive' as in the [documentation](https://developer.amazon.com/en-US/docs/alexa/smapi/voice-permissions-for-timers.html). they have only written the node version. Thus, I am not sure what to replace those two lines with.

**Comment by franklin-lobb** [comment]
I would change this:
```
#handler_input.response_builder.set_card(Card('LinkAccount'))
.ask_sdk_model.response_builder
.add_directive({
```
to this:
```
handler_input.response_builder
.add_directive({
```

**Comment by franklin-lobb** [comment]
However I don't recall that being the right way to ask for permissions.  I'll see if I can find an example of that.

**Comment by danieldhz** [comment]
Hi Franklin! Thanks being with me to figure this out :)) I actually did but as I mentioned (edited), the add_directive is apparently not part of the module even though the python document claim it is. Nevertheless, I do not know what add_directive can be substituted with :(

**Comment by franklin-lobb** [comment]
I've used the add_directive before, so it should be there (unless there was a breaking change removing it, which I think is unlikely).  In that code, it looked like it was trying to use add_directive off of response_builder which was off of ask_sdk_model, but response_builder would be accessed through the handler_input object.

[This sample ](https://github.com/alexa/alexa-cookbook/blob/master/feature-demos/skill-demo-device-location/lambda/py/lambda_function.py) has permission requesting in lines 56-61.

**Comment by franklin-lobb** [comment]
In [line 65](https://github.com/alexa/alexa-cookbook/blob/18895a45db9848e8b2218d4bb58cc2327e9da895/feature-demos/skill-demo-device-location/lambda/py/lambda_function.py#L65) you can see it fetches a device address service client.  you can do the same for a timer management service, which means you can simplify your code and not have to use the requests lib directly.

```
service_client_fact = handler_input.service_client_factory
timer_svc_client = service_client_fact.get_timer_management_service()
all_timers = timer_svc_client.get_timers()
```

The relevant section of the SDK is here: https://github.com/alexa/alexa-apis-for-python/tree/master/ask-sdk-model/ask_sdk_model/services/timer_management.

One other thing to confirm is the that you're using the latest version of the SDK.  I've seen cases where an outdated SDK throws an error because the code calls something not present in that version.  Version 1.23.0 looks to be the latest and timer management was added in 1.22.

**Comment by danieldhz** [comment]
ohh I see. I followed this template [Template](https://dabblelab.com/templates/19-alexa-timers-example-skill) and tried translating to python. But yours is much simpler and elegant to utilize. I will test it now & let you know! Fingers crossed & thank for the follow up :))

**Comment by danieldhz** [comment]
Also quick question: when using "AskforPermission**ConsentCard**" if a user doesn't have an Alexa device with screen (i.e. echo) would the permission be translated via voice instead? As I believe consent card means on screen permission. As well as, will your suggested call get API of user or call a timer? Cause I thought you have to use headers and body to the API to call a timer.

**Comment by franklin-lobb** [comment]
Permissions are typically requested via the Alexa App.  ([Permissions for reminders](https://developer.amazon.com/en-US/docs/alexa/smapi/voice-permissions-for-reminders.html) can be obtained via voice, but so far that's the only one.)

The methods on the service client include:
* create_timer (required parameter is timer_request, which is a ask_sdk_model.services.timer_management.timer_request.TimerRequest)
* pause_timer
* resume_timer
* delete_timer
* delete_timers
* get_timer
* get_timers

You might be able to pass in the timer object you've defined already to the create_timer method as the timer_request parameter.  The python naming convention of creation_behavior instead of creationBehavior might cause that to fail, and if aligning the names in the names doesn't do the trick, then you'd need to build the timer_request step-by-step.

**Comment by danieldhz** [comment]
Hi @franklin-lobb . Thanks for getting back to me. I have read your suggestion multiple times, however; I failed to understand on how I shall implement it. Could you please give me a quick sample on calling a 10 seconds timer as an example.

**Comment by danieldhz** [comment]
p.s: you were right, the add_directive is still there. In fact, voice permission worked! The reason why it was stopping it was that I added "import add_directive" and forgot to remove it since then.

Nevertheless. my template is almost done to be launched to the community. I am only getting a minor error that I just know its a minor bug but not sure how to fix it.

`class LaunchRequestHandler(AbstractRequestHandler):
    def can_handle(self, handler_input):
        return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)
    
    def handle(self, handler_input):
        accessToken= ask_sdk_core.utils.get_api_access_token
        rb = handler_input.response_builder
        request_envelope = handler_input.request_envelope
        permissions = request_envelope.context.system.user.permissions
        if not (permissions and permissions.consent_token):
            logging.info("user hasn't granted reminder permissions")
            return (
                    rb
                    .add_directive(
                        SendRequestDirective(
                            name="AskFor",
                            payload={
                                "@type": "AskForPermissionsConsentRequest",
                                "@version": "1",
                                "permissionScope": "alexa::alerts:timers:skill:readwrite",
                            },
                            token=""
                        )
                    )
                    .response
                )
                                            
        else:
            speak_output = "would you like to set the timer for 20 minutes?"
            if ask_utils.is_request_type("AMAZON.YesIntent")(handler_input): 
                options = {"Authorization": "Bearer " + accessToken,
                            "Content-Type": "application/json"}
                requests.post("https://api.amazonalexa.com/v1/alerts/timers", timer, options)
                speak_output = "timer set for 20 seconds"` 
Error: `[ERROR] 2020-07-15T21:15:39.436Z 789d50b4-7759-4abc-9dce-ac13358bc837 'NoneType' object has no attribute 'object_type'`

**Comment by Shreyas-vgr** [comment]
Duplicate issue, being tracked [here #153](https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/153).
Closing this to avoid duplication.

**Comment by franklin-lobb** [comment]
@danieldhz - It looks like @Shreyas-vgr hooked you up with an example.  LMK if you want something else.

WRT the error - if nothing is showing in CloudWatch logs, check the actual output, perhaps by logging in a response interceptor - it could be malformed json or a problem in what is returned isn't what Alexa is expecting.

Good luck!

**Comment by danieldhz** [comment]
Hi @franklin-lobb How are you doing?
Yes! @Shreyas-vgr Saved my life :) You guys are both life savers. 
Actually, initially, the clouwatch didn't recognize the skill once I deployed it. However, down the road, it is giving this error:
`'REQUIRED_PERMISSIONS' is not defined` for @Shreyas-vgr 's code:
```
class LaunchRequestHandler(AbstractRequestHandler):
def can_handle(self, handler_input):
    return ask_utils.is_request_type("LaunchRequest")(handler_input),ask_utils.is_request_type("AMAZON.YesIntent")(handler_input), ask_utils.is_request_type("AMAZON.NoIntent")(handler_input)

def handle(self, handler_input):
    permissions = handler_input.request_envelope.context.system.user.permissions
    if not (permissions and permissions.consent_token):
        return (
            handler_input.response_builder
            .speak("Please give permissions to set timers using the alexa app.")
            .set_card(
                AskForPermissionsConsentCard(permissions=REQUIRED_PERMISSIONS)
            )
            .response
        )
```
which is really weird because once I initially ran this code in my other skill it had no problem but once I followed @Shreyas-vgr direct skill connection recommendation & launched my skill accordingly from CLI, I am getting that error.

**Comment by franklin-lobb** [comment]
I agree it's weird since it's defined on line 23:

```REQUIRED_PERMISSIONS = ["alexa::alerts:timers:skill:readwrite"]```

**Comment by danieldhz** [comment]
Thanks for your reply @franklin-lobb 
It was actually somehow removed from my file and I trusted my debug console to inform me if it's missing smh lol. Nevertheless, I am now getting 'ServiceClientFactory' object has no attribute 'get_timer_management_service' that i forgot how I fixed last time. lol

**Comment by franklin-lobb** [comment]
That's typically an indication that you need to update your SDK to a more recent version.

**Comment by danieldhz** [comment]
Hi @franklin-lobb I just realized that when I build the skill on dev console i don't get the error, however; when I do it via cli I do get it. Thus, your answer would make sense. At the same timer, my ask-sdk == 1.13.0 & ask-cli ==2.12.0 which i believe both are the latest versions.

**Comment by franklin-lobb** [comment]
This might be hard to track down without knowing a bit more about your setup.  You might try checking the version in your requirements.txt file to ensure that reflects 1.13.  if it requires an older version (either exactly or as a minimum), it might not see a need to update so an older version might get deployed.  It could also be you have the right version installed globally, but the version deployed with your skill's virtual environment is not the right one.  It's a python error, not ASK SDK per se, so I doubt the ask cli version will play into things, especially if the same code works in one place and not the other.

**Comment by danieldhz** [comment]
@franklin-lobb You Are A Certified Genius .
I thought 1.11 should work just as good as 1.13, especially since dev console ran on 1.11, however; as soon as I changed it to 1.13 it started working :)

**Comment by danieldhz** [comment]
HI @franklin-lobb two questions if you don't mind. 
First:
After couple hours of debugging, I realized that as soon as I change {continueWithSkillName} to something else or simply even take out the brackets I get bad request error :(

**Comment by danieldhz** [comment]
Hi @franklin-lobb Fortunately, I've finally built the model. Thus, no more debugging question. Instead, I would just like to know if its possible to open the timer session after the timer ends to minimize user friction. If so, how?

**Comment by danieldhz** [comment]
Hi @franklin-lobb Hi Fortunately, I've finally built the model. Thus, no more debugging question. Instead, I would just like to know if its possible to open the timer session after the timer ends to minimize user friction. If so, how?
As after the would you like to {continuewithskillname}"? no sessions gets opened for user nor does the confirmation text gets read [rep](https://github.com/danieldhz/Alexa_Timer/blob/master/lambda/lambda_function.py)

**Comment by franklin-lobb** [comment]
If I understand what you're looking to do, you'll want to use the [LAUNCH_TASK type of timer](https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-timers-api-reference.html#create-a-timer-operation-launch_task).  (The schema you posted above uses ANNOUNCE.)  After the users answers "yes" to the prompt you set in the timer configuration, then the skill will launch.

Assuming the user confirms the launch, your skill will launch.  I haven't done this bit yet, however it appears (per the docs), it'll launch using [SkillConnections](https://developer.amazon.com/en-US/docs/alexa/custom-skills/use-skill-connections-to-request-tasks.html).  You should log the incoming request during your testing to see what kind of request is being sent, but I would guess it would be SessionResumedRequest based on the docs.

**Comment by danieldhz** [comment]
@franklin-lobb Thanks for your reply. Exactly, I am trying to use Launch_task custom task to forward it to task once the timer goes off, However, as soon as you replace `Announce ` with `Launch_Task` in the json object, Alexa doesn't read the `textToConfirm` despite the doc saying it would. Do you think this is a bug from Alexa itself?
