### ISSUE TITLE
How to open session after timer goes off?

### ISSUE THREAD

**Issue by danieldhz** [alexa/alexa-apis-for-python#12]
Hi All,

How do you reopen the session only after the timer goes off? I appreciate your response in python, if possible.
I tried adding .ask() at the bottom of the func but faced multiple errors.

**Comment by nikhilym** [comment]
Hey @danieldhz , thanks for the issue. I see that you already have a [similar question](https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/153#issuecomment-662804532) in our SDK repo. I am closing this issue so that we can maintain and respond on issues in a better way. Thanks.
