### ISSUE TITLE
Is deleting lists and list items blocked?

### ISSUE THREAD

**Issue by goova8** [alexa/alexa-apis-for-python#3]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request (generic to all classes)
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Want to delete a customer owned list but this does not work
```
handler_input.service_client_factory.get_list_management_service()
list_metadata = list_client.get_lists_metadata()
meta_dict = list_metadata.to_dict()
lists = meta_dict["lists"]
for i in lists:
      if i["name"] == "new_list":
            listId = i["list_id"]
            
list_client.delete_list(list_id = listId)
```

Is this feature blocked or do I need other permissions than <code>["write::alexa:household:list", "read::alexa:household:list"]</code>?

## Context
I am trying to write a skill for my bachelor's thesis that should manipulate lists and purposely perform wrong actions. Therefor I would like to add and delete custom lists and list items.

**Comment by nikhilym** [comment]
Hey @goova8 , sorry for responding late on this. Just to understand the behavior, can you let us know what's the current behavior you are facing w.r.t ``delete_list`` method? What is the service returning?

**Comment by nikhilym** [comment]
Closing the issue. @goova8 , please create a new issue in case you are still facing any problems.
