### ISSUE TITLE
Reminders API broken

### ISSUE THREAD

**Issue by stopmachine** [alexa/alexa-apis-for-python#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request (generic to all classes)
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

The following line should return a list of reminders:
`handler_input.service_client_factory.get_reminder_management_service().get_reminders()`
## Current Behavior
An exception is raised:
```
ask_sdk_core.exceptions.SerializationException: Unable to resolve class ask_sdk_model.services.reminder_management.spoken_info.SpokenInfo from installed modules: No module named 'ask_sdk_model.services.reminder_management.spoken_info'
```
## Possible Solution

Add to `reminder_management/__init__.py`:
`from . import alert_info_spoken_info as spoken_info`

Or edit `alert_info.py` so that the deserialization is done to `ask_sdk_model.services.reminder_management.SpokenInfo` instead of `ask_sdk_model.services.reminder_management.spoken_info.SpokenInfo`

## Your Environment

* ASK SDK Models for Python used: 1.8.0
* ASK SDK for Python used: 1.8.0
* Doesn't look like 1.10.0 fixes this issue

**Comment by nikhilym** [comment]
Hi @stopmachine , thanks for raising the issue. As mentioned these models are auto-generated, but it looks like there is some bug in the process. We will look into fixing it.

**Comment by stopmachine** [comment]
Great, thanks. Even though it's auto-generated maybe consider releasing a hotfix until the root cause is taken care of? After all correctness comes before automation.

**Comment by nikhilym** [comment]
Hey @stopmachine , the latest patch release for ask-sdk-model `1.10.1` fixes this issue. Sorry for responding late.

**Comment by radcorrea** [comment]
Hi! I'm a beginner and sorry for any inconvenience!

I'm having this same problem in version 1.35.0.

This command:

`handler_input.service_client_factory.get_reminder_management_service().get_reminders()`

Return this:

`ask_sdk_core.exceptions.SerializationException: Unable to resolve class ask_sdk_model.services.reminder_management.alert_info_spoken_info.SpokenInfo from installed modules: No module named 'ask_sdk_model.services.reminder_management.alert_info_spoken_info'`

I went back to version 1.10.1 and worked perfectly.
